### ISSUE TITLE
[EXCEPTION ERROR] - Exception when trying to create a user through the Web Portal

### ISSUE THREAD

**Issue by GabrielCin** [S-HealthStack/backend-system#7]
### Description

With the services initialized via docker compose and tables properly created in the database, when trying to create a user via the frontend on the web portal, the error "Server connection failed. Please try again later" is displayed. 
After that, accessing Postgres it is possible to see that the user was created in the database, despite the error presented, but the validation email is not sent.

could anyone help?

### Reproduction steps

```bash
1. Go to 'Web-Portal'
2. Fill in the fields with account information
3. Click on 'Create Account'
4. See error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Logs

```bash
• Inspecting the error log you can find the following:

JSON decoding error: Instantiation of [simple type, class com.samsung.healthcare.account.adapter.auth.supertoken.SuperTokensApi$User] value failed for JSON property email due to missing (therefore NULL) value for creator parameter email which is a non-nullable type; nested exception is com.fasterxml.jackson.module.kotlin.MissingKotlinParameterException: Instantiation of [simple type, class com.samsung.healthcare.account.adapter.auth.supertoken.SuperTokensApi$User] value failed for JSON property email due to missing (therefore NULL) value for creator parameter email which is a non-nullable type\n at [Source: (io.netty.buffer.ByteBufInputStream); line: 1, column: 399] (through reference chain: com.samsung.healthcare.account.adapter.auth.supertoken.SuperTokensApi$AccountResponse[\"user\"]->com.samsung.healthcare.account.adapter.auth.supertoken.SuperTokensApi$User[\"email\"])
```

**Comment by jackvintedge** [comment]
Hi, is this issue have been resolved? I facing the same issue too.

**Comment by jjyun-do** [comment]
@GabrielCin @jackvintedge 

Hello, I apologize for the late response.

Lowering the image version of `supertoken-postgresql` to 6.0 will solve the problem. 
It seems that this happened because we are using the latest images now.

I will modify the docker-compose.yml shortly.

Please let me know if there is anything else I can assist you with.

**Comment by souzawes** [comment]
@jjyun-do 

After applying the suggested modification, I managed to create a user and proceed with the flow of creating studies in the application.

Should we have any doubts in the future, I will get in touch again.

Thank you very much. =)

**Comment by jjyun-do** [comment]
https://github.com/S-HealthStack/S-HealthStack.github.io/pull/22

I'm closing the issue because I've created a pull request to modify the content.
